name: 'HarmonyOS-build'
description: 'This Github action helps build and analyse HMOS libraries'
branding:
  icon: award
  color: red
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: applibgroup/HarmonyOsSdk
        path: SDK
    - name: Copy SDK
      shell: cmd
      id: main
      working-directory: ${{ github.workspace }}
      run: |
        xcopy ${{ github.workspace }}\SDK\config ${{ github.workspace }}\ /Y
        echo %LANG%
    - name: variable
      shell: cmd
      run: echo $GITHUB_REPOSITORY  
    - name: addplugin.bat
      shell: cmd  
      run: ./addplugin.bat  
    - name: build
      env:
        OHOS_SDK_HOME: ${{ github.workspace }}\SDK
      if: always()
      shell: cmd
      run: gradlew assembleDebug sonarqube --info
