name: 'HarmonyOS-build'
description: 'This Github action helps build and analyse HMOS libraries'
branding:
  icon: award
  color: red
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: applibgroup/HarmonyOsSdk
        path: SDK
    - name: Copy SDK
      shell: cmd
      id: main
      working-directory: ${{ github.workspace }}
      run: |
        xcopy ${{ github.workspace }}\SDK\config ${{ github.workspace }}\config\
        echo %LANG%\
        eslint -c config\.eslintrc.json --format json entry --output-file result.json\
        echo %LANG%\
        gradlew assembleDebug sonarqube --info
