name: 'HarmonyOS-build'
description: 'This Github action helps build and analyse HMOS libraries'
branding:
  icon: award
  color: red
runs:
  using: "composite"
  steps:
    - name: Build
      uses: actions/checkout@v2
      with:
        repository: applibgroup/HarmonyOsSdk
        path: SDK
      env:
        OHOS_SDK_HOME: ${{ github.action_path }}/SDK
      shell: cmd
      id: main
      working-directory: ${{ github.workspace }}
      run: |
        ${{ github.action_path }}/run.bat
