name: 'HarmonyOS-build'
description: 'This Github action helps build and analyse HMOS libraries'
branding:
  icon: award
  color: red
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: applibgroup/HarmonyOsSdk
        path: SDK
    - name: Build
      env:
        OHOS_SDK_HOME: ${{ github.workspace }}\SDK
      shell: cmd
      id: main
      working-directory: ${{ github.workspace }}
      run: |
        xcopy ${{ github.workspace }}\SDK\config ${{ github.workspace }}\config\
        xcopy ${{ github.workspace }}\SDK\config\local.properties ${{ github.workspace }}\
        echo %LANG%\
        .\node_modules\.bin\eslint -c ${{ github.workspace }}\SDK\config\.eslintrc.js --format json entry --output-file result.json
        gradlew assembleDebug sonarqube --info
