name: 'HarmonyOS-build'
description: 'This Github action helps build and analyse HMOS libraries'
branding:
  icon: award
  color: red
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: Applib-OpenHarmony/HarmonyOsSdk
        path: SDK
    - name: Copy SDK
      shell: cmd
      id: main
      working-directory: ${{ github.workspace }}
      run: |
        xcopy ${{ github.workspace }}\SDK\config ${{ github.workspace }}\ /Y
        echo %LANG%
#    - name: variable
#      shell: cmd
#      run: echo ${{ github.repository }}  
 #   - name: addplugin.bat
 #     shell: cmd
 #     run: ${{ github.action_path }}\addplugin.bat
    - name: build
      env:
        OHOS_SDK_HOME: ${{ github.workspace }}\SDK
      if: always()
      shell: cmd
      run: | 
        echo %CD%
        cd ${{ github.workspace }}
        echo %CD%
        npm install --fetch-retry-mintimeout=10000 --fetch-retry-maxtimeout=15000 --fetch-retries=1 debug
        node node_modules/@ohos/hvigor/bin/hvigor.js --mode module assembleHap
