name: 'HarmonyOS-build'
description: 'This Github action helps build and analyse HMOS libraries'
branding:
  icon: award
  color: red
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: applibgroup/HarmonyOsSdk
        path: SDK
    - name: Set up JDK 11
      uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
    - uses: actions/setup-node@v2
        with:
          node-version: '14'
    - run: npm install
    - run: npm install eslint
    - name: Copy SDK
      shell: cmd
      id: main
      working-directory: ${{ github.workspace }}
      run: |
        xcopy ${{ github.workspace }}\SDK\config ${{ github.workspace }}\config\
        echo %LANG%
    - name: Run ESlint
      shell: cmd
      run: .\node_modules\.bin\eslint -c config\.eslintrc.json --format json entry --output-file result.json
        echo %LANG%
    - name: build
      env:
        OHOS_SDK_HOME: ${{ github.workspace }}\SDK
      shell: cmd
      run: gradlew assembleDebug sonarqube --info
