name: 'HarmonyOS-build'
description: 'This Github action helps build and analyse HMOS libraries'
branding:
  icon: award
  color: red
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: Applib-OpenHarmony/HarmonyOsSdk
        path: SDK
    - name: Copy SDK
      shell: cmd
      id: main
      working-directory: ${{ github.workspace }}
      run: |
        xcopy ${{ github.workspace }}\SDK\config ${{ github.workspace }}\ /Y
        xcopy ${{ github.workspace }}\node_modules ${{ github.workspace }}\  /E /H /C /I /Y
        echo %LANG%
#    - name: variable
#      shell: cmd
#      run: echo ${{ github.repository }}  
 #   - name: addplugin.bat
 #     shell: cmd
 #     run: ${{ github.action_path }}\addplugin.bat
    - name: build
      env:
        OHOS_SDK_HOME: ${{ github.workspace }}\SDK
      if: always()
      shell: cmd
      run: | 
        cd D:\a\Neumorphism_Smart_Watch\Neumorphism_Smart_Watch\SDK
        dir
        echo %CD%
        cd ${{ github.workspace }}
        echo %CD%
        echo sdk.dir=D\:\\a\\Neumorphism_Smart_Watch\\Neumorphism_Smart_Watch\\SDK >> local.properties
        type local.properties
        npm install --fetch-retry-mintimeout=10000 --fetch-retry-maxtimeout=15000 --fetch-retries=1 debug
        node node_modules/@ohos/hvigor/bin/hvigor.js --mode module assembleHap
